apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-mirror
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
  name: image-mirror
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - update
