apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-mirror
resources:
  - clusterrole.k8s.yaml
  - clusterrolebinding.k8s.yaml
  - deployment.k8s.yaml
  - namespace.k8s.yaml
  - serviceaccount.k8s.yaml
# secretGenerator:
#   - name: image-mirror-creds
#     files:
#       - REGISTRY_PASSWORD
#     literals:
#       - REGISTRY_USERNAME=skhlimr
secretGenerator:
  - name: image-mirror-creds
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
