apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: image-mirror
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
  name: image-mirror
